# Generated by Django 4.0.5 on 2023-09-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFESOR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='puntaje',
            new_name='promedio_general',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='trimestre_parcial',
        ),
        migrations.AddField(
            model_name='notas',
            name='puntaje1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='notas',
            name='puntaje2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='notas',
            name='puntaje3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
