# Generated by Django 4.0.5 on 2023-08-29 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='curso_paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.curso')),
            ],
        ),
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('documento', models.CharField(max_length=10)),
                ('nacimiento_fecha', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('dtest_edad', models.CharField(max_length=30)),
                ('repre_cedula', models.CharField(max_length=10)),
                ('repre_nomape', models.CharField(max_length=70)),
                ('repre_celular', models.CharField(max_length=10)),
                ('repre_convencional', models.CharField(max_length=10)),
                ('repre_gmail', models.EmailField(max_length=100)),
                ('madre_cedula', models.CharField(max_length=10)),
                ('madre_nomape', models.CharField(max_length=70)),
                ('infmadre_celular', models.CharField(max_length=10)),
                ('infmadre_convencional', models.CharField(max_length=10)),
                ('infmadre_gmail', models.EmailField(max_length=100)),
                ('infpadre_cedula', models.CharField(max_length=10)),
                ('infpadre_nomap', models.CharField(max_length=70)),
                ('infpadre_celular', models.CharField(max_length=10)),
                ('infpadre_convencional', models.CharField(max_length=10)),
                ('infpadre_gmail', models.EmailField(max_length=100)),
                ('estsalud_alergias', models.CharField(max_length=10)),
                ('estsalud_tipoalerg', models.CharField(max_length=50)),
                ('estsalud_vacuna19', models.CharField(max_length=10)),
                ('tiene_discapacidad', models.CharField(max_length=10)),
                ('estsalud_discapatipo', models.CharField(max_length=10)),
                ('estemergencia_numerocell1', models.CharField(max_length=10)),
                ('estemergencia_nombre1', models.CharField(max_length=10)),
                ('estemergencia_numcell2', models.CharField(max_length=10)),
                ('estemergencia_nombre2', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(null=True, upload_to='ESTUDIANTE')),
            ],
        ),
        migrations.CreateModel(
            name='etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_et', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_g', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jornada', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paralelo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='parcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parcial', models.CharField(max_length=25)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_td', models.CharField(max_length=75)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_sangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ts', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trimestre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='trimestre_parcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('parcial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.parcial')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.trimestre')),
            ],
        ),
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('curso_paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.curso_paralelo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.estudiantes')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.jornada')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='etnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.etnia'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.genero'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.tipo_documento'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='tipo_sangre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.tipo_sangre'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='usuariox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso_paralelo',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTE.paralelo'),
        ),
    ]
